apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo
  namespace: netcore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-demo
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      imagePullSecrets: 
      - name: myregistrykey 
      containers:
      - name: k8s-demo
        image: registry.cn-hangzhou.aliyuncs.com/gww/k8s-demo:1.3
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /api/values/heath
            port: 32090
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 1   
      
