apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo
  namespace: netcore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-demo
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:  
      imagePullSecrets: 
      - name: aliyun-secret 
      containers:
      - name: k8s-demo
        image: registry.cn-hangzhou.aliyuncs.com/gww/k8s-demo:1.0.1
        imagePullPolicy: IfNotPresent   
        resources:
          requests:
            memory: 128Mi
            cpu: 200m        
          limits:
            memory: 1024Mi
            cpu: 1
        ports:
        - containerPort: 80
        # livenessProbe:
        #   httpGet:
        #     path: /api/values/health
        #     port: 32090
        #   initialDelaySeconds: 15
        #   periodSeconds: 5
        #   timeoutSeconds: 1   
      
