apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: k8s-demo
  namespace: netcore
spec: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-demo
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50