apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-service
  labels: 
    name: k8s-demo-service
  namespace: netcore
spec:
  type: NodePort
  selector:
    app: k8s-demo
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32090
